version: 2
jobs:
  build:
    working_directory: ~/vote-plan
    docker:
      - image: circleci/node:10.16-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-vote-plan-{{ .Branch }}-{{ checksum "package-lock.json" }}
            - v1-vote-plan-{{ .Branch }}-
            - v1-vote-plan-
      - run:
          name: Install npm packages
          command: npm install

      - run:
          name: Get Chrome version
          command: google-chrome --version
      - run:
          name: Get Chrome Stable version
          command: google-chrome-stable --version
      - run:
          name: Get Firefox version
          command: firefox --version

      # ensure the required chrome web driver is installed
      - run:
          name: Ensure Chrome driver is installed
          command: npm run test-ch-driver

      - save_cache:
          key: v1-vote-plan-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - "node_modules"

      - run:
          name: Build app in production mode
          command: npm run build-prod
      - run:
          name: Create Github Pages settings
          command: npm run build-gh-pages
      - run:
          name: Run tests in Firefox
          command: npm run test-ff
      - run:
          name: Run tests in Chrome
          command: npm run test-ch
      - run:
          name: Run Angular end-to-end tests
          command: npm run e2e-ci

      - store_artifacts:
          path: coverage/vote-plan
          destination: coverage

      - store_test_results:
          path: ./junit
      - store_artifacts:
          path: ./junit
          destination: tests
