name: "Build and deploy"
on:
  push:
    branches:
      - main

jobs:
  build:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x

    steps:
      - name: Checkout code
        # https://github.com/actions/checkout
        uses: actions/checkout@v2

      - name: Set up Node ${{ matrix.node-version }}
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v3.1.0
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm packages for automated environment
        # https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
        # https://docs.npmjs.com/cli/v6/commands/npm-ci
        # https://github.com/bahmutov/npm-install
        uses: bahmutov/npm-install@v1

      - name: Run Angular tests
        run: npm run test:ci

      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start

      - name: Build application in production mode
        run: npm run build:prod

      - name: Prepare application for Github Pages
        run: npm run build:gh-pages

      - name: Import GPG key
        # https://github.com/crazy-max/ghaction-import-gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.DEPLOY_GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.DEPLOY_GPG_PASSPHRASE }}
          git-user-signingkey: true
          git-commit-gpgsign: true

      - name: Deploy to GitHub Pages
        # https://github.com/crazy-max/ghaction-github-pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: dist-prod
          fqdn: www.voteplan.org
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
