name: Build vote plan and deploy to Github Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 14.x

    steps:
      - name: Checkout code
        # https://github.com/actions/checkout
        uses: actions/checkout@v2

      - name: Set up Node ${{ matrix.node-version }}
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install npm packages for automated environment
        # https://docs.github.com/en/actions/guides/caching-dependencies-to-speed-up-workflows
        # https://docs.npmjs.com/cli/v6/commands/npm-ci
        # https://github.com/bahmutov/npm-install
        uses: bahmutov/npm-install@v1

      - name: Build application in production mode
        run: npm run build:prod

      - name: Prepare application for Github Pages
        run: npm run build:gh-pages

      - name: Deploy to GitHub Pages
        # see https://github.com/crazy-max/ghaction-github-pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: dist-prod
          fqdn: www.voteplan.org
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
